before:
  hooks:
    - go mod tidy
builds:
  - binary: agora-token-service
    id: agora-token-service
    main: ./cmd/main.go
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
