before:
  hooks:
    - go mod tidy
builds:
  - binary: gora-backend-middleware
    id: gora-backend-middleware
    main: ./cmd/main.go
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
